DROP TABLE IF EXISTS USER;
CREATE SEQUENCE IF NOT EXISTS user_id_seq;
CREATE TABLE USER (
  id BIGINT DEFAULT user_id_seq.nextval PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  balance DECIMAL(20,2),
  created DATETIME DEFAULT CURTIME()
);

DROP TABLE IF EXISTS LOAN;
CREATE TABLE LOAN (
  id INT AUTO_INCREMENT PRIMARY KEY,
  borrower_id INT NOT NULL,
  amount DECIMAL(20, 2) NOT NULL,
  debtor_id INT NOT NULL,
  created DATETIME DEFAULT CURTIME()
);
